# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Create a simple HTML file
RUN echo 'Hi' > /usr/share/nginx/html/index.html

# Expose port 80 to access the web server
EXPOSE 80
